### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by nikil511** [testingtony/balena_youtube#1]
This is exactly what I was looking for...  :-)
Does it work?
Please share current status and instructions of use on readme, maybe I can help with whatever problems you have.

**Comment by testingtony** [comment]
Hi Manolis, 

At the moment, I've just started playing with it. I was hoping to get it running with a pi zero but the performance and network throughput isn't good enough. 

Everything so far is just me ripping off this work https://hub.docker.com/r/alexellis2/streaming 

Give me a day or so and I'll try to get my head around it and knock it into shape.

**Comment by testingtony** [comment]
This latest version seems to be stable enough, it's been streaming from a Pi Zero now for a couple of hours without crashing or losing the connection. That's far longer than every before!
I ended up completely ruining the `master` branch whilst trying to get something running so if you've pulled it previously you might need to force pull.
